server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Главное правило для React Router
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Оптимизация кэширования статики Vite
    location ~* \.(?:css|js|woff2?|eot|ttf|otf|svg|gif|png|jpe?g|ico)$ {
        expires 1y;
        access_log off;
        add_header Cache-Control "public, immutable";
    }
}